"use client";

// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
import { motion } from "framer-motion";
import {
  Scale,
  FileText,
  AlertTriangle,
  Gavel,
  Code,
  //   ShieldBan,
} from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0B0C10] text-slate-900 dark:text-slate-100 transition-colors duration-300 flex flex-col">
      <main className="flex-grow relative z-10 pt-28 pb-20 px-4 sm:px-6">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-16"
          >
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">
              Terms of Service
            </h1>
            <p className="text-lg text-slate-600 dark:text-slate-400">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </motion.div>

          {/* Content Container */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white/70 dark:bg-[#16181D]/70 backdrop-blur-xl border border-slate-200 dark:border-white/10 rounded-2xl p-8 md:p-12 shadow-xl"
          >
            <div className="prose prose-slate dark:prose-invert max-w-none">
              <Section title="1. Acceptance of Terms">
                <p>
                  By accessing or using <strong>DebugDen</strong> (the
                  &quot;Service&quot;), you agree to be bound by these Terms of
                  Service. If you disagree with any part of the terms, you may
                  not access the Service.
                </p>
              </Section>

              <Section title="2. Code Snippets & Licensing">
                <p>
                  DebugDen is a platform for sharing knowledge. By posting code
                  snippets, questions, or answers, you agree that:
                </p>
                <div className="grid md:grid-cols-2 gap-4 mt-4 mb-6">
                  <TermCard
                    icon={<Code className="w-5 h-5 text-blue-500" />}
                    title="Content Ownership"
                    desc="You retain ownership of the content you post, but you grant DebugDen a worldwide, royalty-free license to host and display it."
                  />
                  <TermCard
                    icon={<Scale className="w-5 h-5 text-purple-500" />}
                    title="MIT License Default"
                    desc="Unless otherwise stated, code snippets posted on DebugDen are deemed to be shared under the MIT License for community use."
                  />
                </div>
              </Section>

              <Section title="3. User Conduct">
                <p>
                  You agree not to engage in any of the following prohibited
                  activities:
                </p>
                <ul className="list-disc pl-5 space-y-2 mt-4 text-slate-700 dark:text-slate-300">
                  <li>Posting malicious code, viruses, or harmful scripts.</li>
                  <li>
                    Harassing, bullying, or intimidating other developers.
                  </li>
                  <li>
                    Spamming questions or answers to artificially inflate your
                    reputation score.
                  </li>
                  <li>
                    Attempting to reverse engineer or disrupt the Service&apos;s
                    infrastructure.
                  </li>
                </ul>
              </Section>

              <Section title="4. AI Generated Content">
                <div className="bg-amber-50 dark:bg-amber-500/10 border-l-4 border-amber-500 p-4 rounded-r-lg my-6">
                  <div className="flex items-start gap-3">
                    <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-500 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-bold text-amber-900 dark:text-amber-100 text-sm uppercase mb-1">
                        Disclaimer
                      </h4>
                      <p className="text-sm text-amber-800 dark:text-amber-200">
                        Our &quot;Generate AI Answer&quot; feature uses third-party
                        Large Language Models. AI can make mistakes. You
                        acknowledge that code generated by AI may contain bugs,
                        security vulnerabilities, or hallucinations. Always
                        review code before using it in production.
                      </p>
                    </div>
                  </div>
                </div>
              </Section>

              <Section title="5. Termination">
                <p>
                  We may terminate or suspend your account immediately, without
                  prior notice or liability, for any reason whatsoever,
                  including without limitation if you breach the Terms. Upon
                  termination, your right to use the Service will immediately
                  cease.
                </p>
              </Section>

              <Section title="6. Limitation of Liability">
                <p>
                  In no event shall DebugDen, nor its directors, employees,
                  partners, agents, suppliers, or affiliates, be liable for any
                  indirect, incidental, special, consequential or punitive
                  damages, including without limitation, loss of profits, data,
                  use, goodwill, or other intangible losses, resulting from your
                  access to or use of or inability to access or use the Service.
                </p>
              </Section>

              <div className="mt-12 pt-8 border-t border-slate-200 dark:border-white/10 flex items-center gap-4 text-slate-500 dark:text-slate-400 text-sm">
                <Gavel className="w-5 h-5" />
                <p>
                  These terms are governed by the laws of India/Maharashtra.
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </main>
    </div>
  );
}

// --- Helper Components ---

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mb-10">
      <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
        <FileText className="w-6 h-6 text-slate-400" />
        {title}
      </h2>
      <div className="text-slate-600 dark:text-slate-300 leading-relaxed">
        {children}
      </div>
    </div>
  );
}

function TermCard({
  icon,
  title,
  desc,
}: {
  icon: React.ReactNode;
  title: string;
  desc: string;
}) {
  return (
    <div className="bg-slate-50 dark:bg-white/5 p-4 rounded-xl border border-slate-200 dark:border-white/5">
      <div className="flex items-center gap-3 mb-2">
        <div className="p-2 bg-white dark:bg-white/10 rounded-lg shadow-sm">
          {icon}
        </div>
        <h3 className="font-semibold text-slate-900 dark:text-white">
          {title}
        </h3>
      </div>
      <p className="text-sm text-slate-600 dark:text-slate-400">{desc}</p>
    </div>
  );
}
